import {
    AstroIcon,
    C,
    GitHub,
    GitLab,
    HTML,
    CSS,
    JavaScript,
    MD,
    Nextjs,
    Python,
    MySQL,
    React as ReactIcon,
    SQLServer,
    SQLIcon,
    SASS,
    TailwindIcon,
    TypeScript,
  } from "./icons";
  
  export const iconosTecnologias = {
    Astro: AstroIcon,
    C: C,
    GitHub: GitHub,
    GitLab: GitLab,
    HTML: HTML,
    CSS: CSS,
    JavaScript: JavaScript,
    MD: MD,
    Nextjs: Nextjs,
    Python: Python,
    MySQL: MySQL,
    React: ReactIcon,
    SQLServer: SQLServer,
    SQL: SQLIcon,
    SASS: SASS,
    Tailwind: TailwindIcon,
    TypeScript: TypeScript,
    "Next.js": Nextjs,
    "Pandas": Python,
    "Jupyter": Python,
    "T-SQL": SQLServer,
    "Obsidian": MD,
    "cURL": C,
  };